apiVersion: v1
kind: Service
metadata:
  name: azure-function-service
  labels:
    app: azure-function
spec:
  type: LoadBalancer
  selector:
    app: azure-function
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

